routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('inventory')->group (function () {
    Route::get('/', 'InventoryController@index');
    Route::get('dashboard', 'InventoryController@dashboard')->name('inventory.dashboard');
  //  Route::get('phonebook', 'PhonebookController@phonebook')->name('inventory.phonebook');
    Route::resource('phonebook', 'PhonebookController');
    Route::get('apiphonebook', 'PhonebookController@apiPhonebook')->name('apiphonebook');


});

//DEPARTMENT
Route::prefix('humanresource')->group (function () {

    Route::resource('department', 'DepartmentController');
    Route::get('apidepartment', 'DepartmentController@apiDepartment')->name('apidepartment');


    Route::resource('employee', 'humanresource\EmployeeController');
    Route::get('apiemployee', 'humanresource\EmployeeController@apiEmployee')->name('apiemployee');




});

resources/views/_includes/layouts/footer.blade.php
<div class="nov-footer">
    <div class="nov-footer-container">
        <span>created by &copy; <a href="https://fb.com/unohito" target="_blank"><b>dennissnov</b></a> | <a href="https://www.cine-pilot.net/" target="_blank"> <b>cinepilot </b></a>2018</span>
    </div>
</div>

resources/views/_includes/layouts/nav.blade.php
    <div class="nov-top-navbar">
      <nav class="navbar navbar-default navbar-static-top">
             <div class="nov-navbar-container"> 
                <div class="navbar-header">
                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ route('inventory.dashboard') }}">
                        {{ config('app.name', 'CINEPILOT') }}
                    </a>
                </div>
                <button class="nov-toggle fa fa-toggle-on"></button>

                <div class="nav nov-navbar-right">
                    <!-- Authentication Links -->
                    @guest
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endguest
                </div>
            </div><!--END OF NOV NAVBAR -->

            
        </nav>


</div>

resources/views/_includes/layouts/sidebar.blade.php
<nav class="nov-sidebar nov-open" >
    <div class="nov-sidebar-container">
        <ul class="nov-sidebar-list">
            <li class="nov-sidebar-profile">
                <div class="sidebar-profile-container">
                    <ul>
                        <li class="sidebar-profile-photo">
                            <img src="{{ asset('images/logo_fixed.jpg') }}" />
                        </li>
                        <li class="sidebar-profile-name">
                            <span>{{strtoupper(Auth::user()->name )}}</span>
                        </li>
                        <li class="sidebar-profile-email">
                            <span>{{ Auth::user()->email }}</span>
                        </li>
                    </ul>
                </div>
            </li>
               
            <li class="nov-sidebar-menu ">
                <a href="{{ route('inventory.dashboard')}}"><i class="fa fa-home"></i><span>DASHBOARD</span></a>
            </li>
            <li class="nov-sidebar-menu">
               <!-- <a class="accordion-toggle collapsed toggle-switch" data-toggle="collapse" href="#submenu-1"> -->
                <a class="accordion-toggle collapsed" data-toggle="collapse" href="#submenu-1">
                    <i class="fa fa-camera-retro"></i>
                    <span>INVENTORY</span>
                </a>
               <!--  <ul id="submenu-1" class="panel-collapse collapse panel-switch" role="menu">-->
                <ul id="submenu-1" class="collapse" role="menu">
                    <li class="nov-sidebar-menu"><a href="#"><i class="fa fa-cube"></i><span>Category</span></a></li>
                    <li class="nov-sidebar-menu"><a href="#"><i class="fa fa-truck"></i><span>Barang Masuk</span></a></li>
                    <li class="nov-sidebar-menu"><a href="#"><i class="fa fa-plane"></i><span>Barang Keluar</span></a></li>
                    <li class="nov-sidebar-menu"><a href="#"><i class="fa fa-building"></i><span>Data Barang</span></a></li>
                    <li class="nov-sidebar-menu"><a href="#"><i class="fa fa-chain-broken"></i><span>Barang Rusak</span></a></li>
                    <li class="nov-sidebar-menu"><a href="#"><i class="fa fa-handshake-o"></i><span>Pengajuan Barang</span></a></li>
                </ul>
            </li>
            <li class="nov-sidebar-menu" >
                <a class="accordion-toggle collapsed" id="nov-sidebar-hrd" data-toggle="collapse" href="#submenu-2">
                    <i class="fa fa-grav"></i>
                    <span>HUMAN RESOURCE</span>
                </a>
               <!--  <ul id="submenu-1" class="panel-collapse collapse panel-switch" role="menu">-->
                <ul id="submenu-2" class="collapse" role="menu">
                    <li class="nov-submenu nov-sidebar-menu"><a href="{{ route('department.index')}}"><i class="fa fa-sitemap"></i><span>Department</span></a></li>
                    <li class="nov-submenu nov-sidebar-menu"><a href="{{ route('employee.index')}}"><i class="fa fa-resistance"></i><span>Employee</span></a></li>
                    <li class="nov-submenu nov-sidebar-menu"><a href="#"><i class="fa fa-users"></i><span>Outsource</span></a></li>
                </ul>
            </li>
            <li class="nov-sidebar-menu">
                <a href="{{ route('phonebook.index')}}"><i class="fa fa-address-book"></i><span> PHONEBOOK</span></a>
            </li>

        </ul>
    </div>
</nav>